### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by alexeykudinkin** [breandan/idear#17]
We need some sort of the presentation scenario, which looks connected not just a bunch of random commands being triggered at the show-off, but rather a connected story should be conveyed.

**Comment by sweetybanana** [comment]
It looks like if we could debug something and fix a simple bug, using only voice commands that'll be great. 

I think fixing some NPE by adding not null check anywhere will fit.

Seems like a lot of work though, but possible.

**Comment by sweetybanana** [comment]
So we need to:

- set exception breakpoint
- locate to problem
- surround it with not null check
- run all this stuff again

**Comment by sweetybanana** [comment]
What are your thoughts on this?

**Comment by alexeykudinkin** [comment]
Are we capable to run configurations already?

**Comment by sweetybanana** [comment]
Can now
