### ISSUE TITLE
Syntax for Googling Things

### ISSUE THREAD

**Issue by breandan** [breandan/idear#9]
@alexeykudinkin Perhaps we should just use the [Google Speech API](https://github.com/gillesdemey/google-speech-v2/) for freeform "what is"-type queries if we're going to send the user to the search engine anyway?

**Comment by sweetybanana** [comment]
Oh yeah!!! It will be great, instead of googling and browser opening we could request google for it and show quick doc!!! Nice!!

**Comment by alexeykudinkin** [comment]
Yeah, that should work.

**Comment by breandan** [comment]
Another bad hack incoming. Since Sphinx4 doesn't support allow us to access the utterance data directly, we dump the .wav files to disk, then fire a REST request to get the speech result. Finally, we need a way to open up URL in the browser.

* http://stackoverflow.com/questions/23159506/saving-utterance-to-audio-file-with-sphinx4
* https://sourceforge.net/p/cmusphinx/discussion/sphinx4/thread/50b9aa29/
